package org.zywko.week_3.botega;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class GotocloudazureTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
//    System.setProperty("webdriver.chrome.driver","C:\\Users\\zywko\\IdeaProjects\\test_automation\\src\\main\\resources\\chromedriver.exe");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void gotocloudazure() {
    driver.get("https://bottega.com.pl/");
    driver.manage().window().setSize(new Dimension(1280, 680));
    driver.findElement(By.cssSelector(".icons-grid-item:nth-child(18) img")).click();
    driver.findElement(By.id("filter-keywords")).click();
    driver.findElement(By.id("filter-keywords")).sendKeys("azure");
    driver.findElement(By.id("filter-keywords")).sendKeys(Keys.ENTER);
    driver.findElement(By.cssSelector(".fa-search")).click();
    js.executeScript("window.scrollTo(0,900)");
    driver.findElement(By.cssSelector(".odd:nth-child(1) .more")).click();
    js.executeScript("window.scrollTo(0,646.6666870117188)");
  }
}
