package org.zywko.week_3.selenium_ide.botega;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;

import java.util.*;

public class ClickallheaderbottomsTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    ChromeOptions options = new ChromeOptions();
    options.addArguments("--remote-allow-origins=*");
    System.setProperty("webdriver.chrome.driver", "C:\\Users\\zywko\\IdeaProjects\\test_automation\\src\\main\\resources\\chromedriver.exe");
    driver = new ChromeDriver(options);
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void clickallheaderbottoms() {
    driver.get("https://bottega.com.pl/");
    driver.manage().window().setSize(new Dimension(1280, 680));
    driver.findElement(By.cssSelector(".main-menu-item:nth-child(1) > a")).click();
    driver.findElement(By.cssSelector(".main-menu-item:nth-child(2) > a")).click();
    driver.findElement(By.cssSelector(".main-menu-item:nth-child(3) > a")).click();
    driver.findElement(By.cssSelector(".main-menu-item:nth-child(4) > a")).click();
    driver.findElement(By.cssSelector(".main-menu-item:nth-child(5) > a")).click();
    driver.findElement(By.cssSelector(".main-menu-item:nth-child(6) > a")).click();
    driver.findElement(By.linkText("PL")).click();
    driver.findElement(By.linkText("EN")).click();
  }
}
