package org.zywko.week_3.selenium_ide.allegro;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;

import java.util.*;

public class LogintryTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    ChromeOptions options = new ChromeOptions();
    options.addArguments("--remote-allow-origins=*");
    System.setProperty("webdriver.chrome.driver", "C:\\Users\\zywko\\IdeaProjects\\test_automation\\src\\main\\resources\\chromedriver.exe");
    driver = new ChromeDriver(options);
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void logintry() {
    driver.get("https://allegro.pl/");
    driver.manage().window().setSize(new Dimension(1280, 680));
    driver.findElement(By.cssSelector(".eut9m > .mpof_z0")).click();
    driver.findElement(By.cssSelector(".\\_b4f07_WuuMm")).click();
    driver.findElement(By.id("login")).click();
    driver.findElement(By.id("login")).sendKeys("notexists@domain.com");
    js.executeScript("window.scrollTo(0,81.33333587646484)");
    driver.findElement(By.id("password")).sendKeys("thisislongpassword");
    driver.findElement(By.cssSelector(".msts_enp")).click();
    js.executeScript("window.scrollTo(0,142)");
  }
}
